apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdrive
spec:
  selector:
    matchLabels:
      name: cdrive
  replicas: 1
  template:
    metadata:
      labels:
        name: cdrive
    spec:
      containers:
        - name: cdrive
          image: "docker.io/kaushikc92/cdrive:latest"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
            - name: AWS_STORAGE_BUCKET_NAME
              value: ""
