# Generated by Django 2.2.4 on 2019-08-07 20:30

from django.db import migrations, models
import django.db.models.deletion
import drive_api.models

def create_home(apps, schema_editor):
    CDriveFolder = apps.get_model('drive_api', 'CDriveFolder')
    home_folder = CDriveFolder(
        name = 'users',
        parent = None,
        owner = None
    )
    home_folder.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_api', '0001_initial'),
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDriveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cdrive_file', models.FileField(upload_to=drive_api.models.file_path)),
                ('size', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefile_owner', to='user_mgmt.CDriveUser')),
            ],
        ),
        migrations.CreateModel(
            name='CDriveFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefolder_owner', to='user_mgmt.CDriveUser')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefolder_parent', to='drive_api.CDriveFolder')),
            ],
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('V', 'View'), ('E', 'Edit')], max_length=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folderpermission_app', to='apps_api.CDriveApplication')),
                ('cdrive_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folderpermission_folder', to='drive_api.CDriveFolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folderpermission_user', to='user_mgmt.CDriveUser')),
            ],
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('V', 'View'), ('E', 'Edit')], max_length=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filepermission_app', to='apps_api.CDriveApplication')),
                ('cdrive_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filepermission_file', to='drive_api.CDriveFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filepermission_user', to='user_mgmt.CDriveUser')),
            ],
        ),
        migrations.AddField(
            model_name='cdrivefile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefile_parent', to='drive_api.CDriveFolder'),
        ),
        migrations.RunPython(create_home),
    ]
