# Generated by Django 2.2.2 on 2019-08-03 00:54

from django.db import migrations, models
import django.db.models.deletion
import drive_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_mgmt', '0001_initial'),
        ('apps_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDriveFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('edit_app', models.ManyToManyField(related_name='cdrivefolder_edit_app', to='apps_api.CDriveApplication')),
                ('edit_user', models.ManyToManyField(related_name='cdrivefolder_edit_user', to='user_mgmt.CDriveUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefolder_owner', to='user_mgmt.CDriveUser')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefolder_parent', to='drive_api.CDriveFolder')),
                ('share_app', models.ManyToManyField(related_name='cdrivefolder_share_app', to='apps_api.CDriveApplication')),
                ('share_user', models.ManyToManyField(related_name='cdrivefolder_share_user', to='user_mgmt.CDriveUser')),
                ('view_app', models.ManyToManyField(related_name='cdrivefolder_view_app', to='apps_api.CDriveApplication')),
                ('view_user', models.ManyToManyField(related_name='cdrivefolder_view_user', to='user_mgmt.CDriveUser')),
            ],
        ),
        migrations.CreateModel(
            name='CDriveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cdrive_file', models.FileField(upload_to=drive_api.models.file_path)),
                ('size', models.IntegerField()),
                ('edit_app', models.ManyToManyField(related_name='cdrivefile_edit_app', to='apps_api.CDriveApplication')),
                ('edit_user', models.ManyToManyField(related_name='cdrivefile_edit_user', to='user_mgmt.CDriveUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefile_owner', to='user_mgmt.CDriveUser')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdrivefile_parent', to='drive_api.CDriveFolder')),
                ('share_app', models.ManyToManyField(related_name='cdrivefile_share_app', to='apps_api.CDriveApplication')),
                ('share_user', models.ManyToManyField(related_name='cdrivefile_share_user', to='user_mgmt.CDriveUser')),
                ('view_app', models.ManyToManyField(related_name='cdrivefile_view_app', to='apps_api.CDriveApplication')),
                ('view_user', models.ManyToManyField(related_name='cdrivefile_view_user', to='user_mgmt.CDriveUser')),
            ],
        ),
    ]
