# Generated by Django 2.2.2 on 2019-08-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDriveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('image', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=300)),
            ],
        ),
    ]
